# Generated by Django 5.0.6 on 2024-08-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pati_name', models.CharField(max_length=255)),
                ('pati_phone', models.CharField(max_length=10)),
                ('pati_email', models.EmailField(max_length=254)),
                ('book_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.department')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.doctors')),
            ],
        ),
    ]
